# Generated by Django 5.0.3 on 2024-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anim_Nome', models.CharField(max_length=45)),
                ('Anim_Especie', models.CharField(max_length=45)),
                ('Anim_Raca', models.CharField(max_length=45)),
                ('Anim_Sexo', models.CharField(max_length=45)),
                ('Anim_Idade', models.IntegerField()),
                ('Anim_Peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Anim_Caracteristicas', models.CharField(max_length=200)),
                ('Tutor_idTutor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aten_Data', models.DateField()),
                ('Aten_Obs', models.CharField(max_length=200)),
                ('Animal_idAnimal', models.IntegerField()),
                ('Animal_Tutor_idTutor', models.IntegerField()),
                ('Clinica_idClinica', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clin_Estabelecimento', models.CharField(max_length=45)),
                ('Clin_Endereco', models.CharField(max_length=200)),
                ('Clin_Bairro', models.CharField(max_length=45)),
                ('Clin_Veterinario', models.CharField(max_length=45)),
                ('Clin_CRM', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tut_Nome', models.CharField(max_length=200)),
                ('Tut_Endereco', models.CharField(max_length=200)),
                ('Tut_Bairro', models.CharField(max_length=45)),
                ('Tut_Fone', models.CharField(max_length=45)),
                ('Tut_CPF', models.CharField(max_length=45)),
                ('Tut_RG', models.CharField(max_length=45)),
                ('Tut_Ong', models.SmallIntegerField()),
            ],
        ),
    ]
