# Generated by Django 5.0.3 on 2024-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='Anim_Caracteristicas',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='Anim_Especie',
            field=models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino')], default='Canino', max_length=45),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='Anim_Sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], default='Macho', max_length=45),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='Aten_Data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='Aten_Obs',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='Tut_Ong',
            field=models.SmallIntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
    ]
