# Generated by Django 5.0.3 on 2024-04-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='Tutor_idTutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo11.tutormodel'),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='Animal_Tutor_idTutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo11.tutormodel'),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='Clinica_idClinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo11.clinicamodel'),
        ),
    ]
