-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 16:18:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tutor` (
  `idTutor` INT NOT NULL AUTO_INCREMENT,
  `Tut_Nome` VARCHAR(200) NOT NULL,
  `Tut_Endereco` VARCHAR(200) NOT NULL,
  `Tut_Bairro` VARCHAR(45) NOT NULL,
  `Tut_Fone` VARCHAR(45) NOT NULL,
  `Tut_CPF` VARCHAR(45) NOT NULL,
  `Tut_RG` VARCHAR(45) NOT NULL,
  `Tut_Ong` TINYINT NOT NULL,
  PRIMARY KEY (`idTutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Animal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `Anim_Nome` VARCHAR(45) NOT NULL,
  `Anim_Especie` VARCHAR(45) NOT NULL DEFAULT 'Canino ou Felino',
  `Anim_Raca` VARCHAR(45) NOT NULL,
  `Anim_Sexo` VARCHAR(45) NOT NULL,
  `Anim_Idade` INT NOT NULL,
  `Anim_Peso` DECIMAL NOT NULL,
  `Anim_Caracteristicas` VARCHAR(200) NOT NULL,
  `Tutor_idTutor` INT NOT NULL,
  PRIMARY KEY (`idAnimal`, `Tutor_idTutor`),
  CONSTRAINT `fk_Animal_Tutor`
    FOREIGN KEY (`Tutor_idTutor`)
    REFERENCES `mydb`.`Tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clinica` (
  `idClinica` INT NOT NULL AUTO_INCREMENT,
  `Clin_Estabelecimento` VARCHAR(45) NOT NULL,
  `Clin_Endereco` VARCHAR(200) NOT NULL,
  `Clin_Bairro` VARCHAR(45) NOT NULL,
  `Clin_Veterinario` VARCHAR(45) NOT NULL,
  `Clin_CRM` VARCHAR(45) NOT NULL,
  `Clin_Fone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idClinica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atendimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atendimento` (
  `idAtendimento` INT NOT NULL AUTO_INCREMENT,
  `Aten_Data` DATE NOT NULL,
  `Aten_Obs` VARCHAR(200) NOT NULL,
  `Animal_idAnimal` INT NOT NULL,
  `Animal_Tutor_idTutor` INT NOT NULL,
  `Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`idAtendimento`, `Animal_idAnimal`, `Animal_Tutor_idTutor`, `Clinica_idClinica`),
  CONSTRAINT `fk_Atendimento_Animal1`
    FOREIGN KEY (`Animal_idAnimal` , `Animal_Tutor_idTutor`)
    REFERENCES `mydb`.`Animal` (`idAnimal` , `Tutor_idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` int NOT NULL,
  `Usuario_Nome` varchar(45) NOT NULL,
  `Usuario_Registro` varchar(45) NOT NULL,
  `Usuario_CPF` varchar(45) NOT NULL,
  `Usuario_Senha` decimal(8,0) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE KEY `Usuario_Nome_UNIQUE` (`Usuario_Nome`),
  UNIQUE KEY `idUsuario_UNIQUE` (`idUsuario`),
  UNIQUE KEY `Usuario_Registro_UNIQUE` (`Usuario_Registro`),
  UNIQUE KEY `Usuario_CPF_UNIQUE` (`Usuario_CPF`),
  UNIQUE KEY `Usuario_Senha_UNIQUE` (`Usuario_Senha`)
  )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
    `idUsuario` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`idUsuario`)
) ENGINE = InnoDB;

INSERT INTO `mydb`.`Usuarios` (username, password, is_admin) 
VALUES ('admin', MD5('senha123'), 1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
